AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NookTrip Backend Functions

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024

Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - uat
    - prod

Resources:
  NookTripSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "nooktrip-secrets-${env}"
      Description: "Secrets for NookTrip API"

  ITINERARIESFUNCTION:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: itineraries/
      FunctionName: !Sub "Itineraries-${env}"
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::730335245225:role/master_lambda_role
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ID_NAME: !Ref NookTripSecrets
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /itineraries
            Method: POST

  EMAILSFUNCTION:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: emails/
      FunctionName: !Sub "Emails-${env}"
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::730335245225:role/master_lambda_role
      Runtime: python3.11
      Architectures:
      - x86_64
      Environment:
        Variables:
          SECRET_ID_NAME: !Ref NookTripSecrets
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /emails
            Method: POST

Outputs:
  NookTripSecretsName:
    Description: "Secrets Manager for NookTrip API credentials"
    Value: !Ref NookTripSecrets
  ItinerariesApi:
    Description: "API Gateway endpoint URL for Itineraries function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/itineraries/"
  EmailsApi:
    Description: "API Gateway endpoint URL for Emails function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/emails/"
