"""Add feedbacks

Revision ID: 44fbc293a906
Revises: 9188ef4ad226
Create Date: 2024-10-07 21:50:29.248465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fbc293a906'
down_revision: Union[str, None] = '9188ef4ad226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Enum('LIKE', 'DISLIKE', name='feedbacktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['selected_itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_feedback_id'), 'itinerary_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_feedback_id'), table_name='itinerary_feedback')
    op.drop_table('itinerary_feedback')
    # ### end Alembic commands ###
