"""Create SelectedItinerary table

Revision ID: 9188ef4ad226
Revises: cc5d5d58db6a
Create Date: 2024-09-23 19:30:34.784413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9188ef4ad226'
down_revision: Union[str, None] = 'cc5d5d58db6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('itinerary_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_itineraries_email'), 'selected_itineraries', ['email'], unique=False)
    op.create_index(op.f('ix_selected_itineraries_id'), 'selected_itineraries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selected_itineraries_id'), table_name='selected_itineraries')
    op.drop_index(op.f('ix_selected_itineraries_email'), table_name='selected_itineraries')
    op.drop_table('selected_itineraries')
    # ### end Alembic commands ###
