"""Initial migration

Revision ID: cc5d5d58db6a
Revises: 
Create Date: 2024-07-22 01:30:18.040005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5d5d58db6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_emails_email'), 'user_emails', ['email'], unique=True)
    op.create_index(op.f('ix_user_emails_id'), 'user_emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_emails_id'), table_name='user_emails')
    op.drop_index(op.f('ix_user_emails_email'), table_name='user_emails')
    op.drop_table('user_emails')
    # ### end Alembic commands ###
