on:
  push:
    branches:
    - dev
    - uat
    - prod
    paths:
    - 'NOOK-FUNCTIONS/**'

jobs:
  NOOK-FUNCTIONS-sam:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ github.ref == 'refs/heads/prod' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ github.ref == 'refs/heads/prod' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Extract branch name
      id: branch-name
      run: echo "::set-output name=branch-name::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build SAM app
      working-directory: ./NOOK-FUNCTIONS
      run: sam build

    - name: Deploy SAM app
      working-directory: ./NOOK-FUNCTIONS
      run: |
        if [ "${{ steps.branch-name.outputs.branch-name }}" == "prod" ]; then
          sam deploy --stack-name ZOHO-${{ steps.branch-name.outputs.branch-name }} --s3-bucket nt-cf-prod-ohio --capabilities CAPABILITY_IAM --parameter-overrides env=${{ steps.branch-name.outputs.branch-name }}
        else
          sam deploy --stack-name ZOHO-${{ steps.branch-name.outputs.branch-name }} --s3-bucket nt-cf-ohio --capabilities CAPABILITY_IAM --parameter-overrides env=${{ steps.branch-name.outputs.branch-name }}
        fi
